### ISSUE TITLE
Remove all libs from public/asses/libs

### ISSUE THREAD

**Issue by michelboaventura** [eubr-bigsea/ember-citron#143]
We need to include our libraries with npm, not copy and paste its files on public/assets. We also need to remove them from index.html

**Comment by michelboaventura** [comment]
@pedrobernardina, @gfranciscani

**Comment by guerra** [comment]
@michelboaventura, please report the status of this task.

**Comment by guerra** [comment]
@pedrobernardina @gfranciscani 
Check each lib on file /ember-cli-build.js, beginning on line 31, if any of those dependencies have node support.

**Comment by gfranciscani** [comment]
Resolved!
