### ISSUE TITLE
Deploy a staging environment

### ISSUE THREAD

**Issue by guerra** [eubr-bigsea/ember-citron#182]
After @waltersf finishes all dockers compose scripts and issue #180 is done, deploy a staging environment .

**Comment by guerra** [comment]
@waltersf, do you need help?

**Comment by waltersf** [comment]
@guerra I'm testing the solution from @mgonc about how to change Ember configuration. My implementation seams to be working. 
Next steps are run everything from a docker-compose script (in progress).

**Comment by waltersf** [comment]
@guerra Matheus is fixing a bug in the integration between Citron and other components when authenticating users in Thorn.

**Comment by waltersf** [comment]
Available at http://lemonade.ctweb.inweb.org.br. 
It is not working outside our network because I will configure the firewall soon
