### ISSUE TITLE
Base URL for caipirinha is hard-coded in component

### ISSUE THREAD

**Issue by waltersf** [eubr-bigsea/ember-citron#202]
Component app/components/visualizations/generic-visu.js is using "http://beta.ctweb.inweb.org.br/caipirinha/visualizations" as base URL for caipirinha instead of using Ember environ variable.

**Comment by michelboaventura** [comment]
@gfranciscani

**Comment by guerra** [comment]
@gfranciscani, we need a solution for this asap.

**Comment by waltersf** [comment]
PR #208 solved this issue
