### ISSUE TITLE
Data Operations don't retrieve attributes from backend dataflow

### ISSUE THREAD

**Issue by ojvictor** [eubr-bigsea/ember-citron#206]
The interface operations don't retrieve attributes information from the data flow.  

The attributes form is empty. 

Some operators like Projection/Select columns, clean missing must retrieve attributes from dataflow and allow users to select them.

**Comment by michelboaventura** [comment]
This is a duplicate of https://github.com/eubr-bigsea/ember-citron/issues/150

**Comment by ojvictor** [comment]
Sorry, I didn't associate this issue to #150. 
For organization purpose, I will close it.
